AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'tasks/release.rake'
    - '*.gemspec'
    - 'Gemfile'
    - 'Rakefile'

Metrics/LineLength:
  Max: 115

Style/SpecialGlobalVars:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Performance/Caller:
  Enabled: false
